
#oss
aliyun:
  accessKeyId: LTAI4FkV2uV8jK3igMZTiDqM
  accessKeySecret: lycHTrho8UwamlVTwnFntY7ScF9ojc
  bucketName: lovezz-app
  endpoint: http://oss-cn-shenzhen.aliyuncs.com
  fileDir: userImg/
application:
  baidu:
    ak: 9IzlUah1qQkqmZPw6F9GOIWmYGGTiaXt
    server: https://api.map.baidu.com
  tianxin:
    key: 02e7187e53059f3dd526a1ca353e5007
    server: http://api.tianapi.com

# 开启httpclient
feign:
  httpclient:
    enabled: true
logging:
  level:
    ROOT: INFO
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  mapper-locations: classpath:/xml/*Mapper.xml
  typeAliasesPackage: com.qltime.entity
server:
  port: 8091
  servlet:
    session:
      timeout: 2592000s
spring:
  application:
    name: qltime
  datasource:
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat,wall,log4j
    initialSize: 5
    maxActive: 20
    maxPoolPreparedStatementPerConnectionSize: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 5
    password: root
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://8.130.101.229:3307/qltime?serverTimezone=GMT%2B8&useSSL=false
    username: root
    validationQuery: SELECT 1 FROM DUAL
  mail:
    default-encoding: UTF-8
    host: 220.181.12.18
    password: qq352642663..
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
            port: 465
          starttls:
            enable: true
            required: true
    to: 352642663@qq.com
    username: 13078229267@163.com
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 100MB
  thymeleaf:
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html

# 微信推送
wx:
  miniapp:
    appSecret: d6d3e4216357ae924dede09fb0e9fb84
    appid: wx9d47085f918587dc
  templatelist:
    - templateId: _SXDQxn4ogXe8i1QGhyxT0TGIlCcOR9An0oONgts8-Y
      type: DAILY_BOY
    - templateId: _SXDQxn4ogXe8i1QGhyxT0TGIlCcOR9An0oONgts8-Y
      type: DAILY_GIRL
      # 微信新消息提醒
    - templateId: gNsrAQuc3vW3r1MbfOMeU_ETzQ_U7Obf1lIdE4xV2qE
      type: NOTICE
  wxPush:
    appId: wxeaab9360ff90ee8a
    appSecret: 2df00a586624f4379c063eeb709532e3
